author: Chris Williams
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-IRC-Plugin-POE-Knee
no_index:
  directory:
    - inc
    - t
requires:
  Math::Random: 0.69
  POE::Component::IRC: 5.06
  Time::HiRes: 0
version: 1.00
